name: contributer-badge
on:
  workflow_dispatch: {}
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  call-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kaizencc/github-merit-badger@main
        id: badger
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          badges: '[first,second,third]'
          thresholds: '[0,1,2]'
          badge-descriptions: '[you are first!,you are second!,you are third!]'
          badge-type: 'achievement'
      # - uses: kaizencc/github-merit-badger@main
      #   id: contributor-badge-hotlist
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     labels: '1 :trophy:,top 3 :fire:,top 5 :sunglasses:'
      #     buckets: '1,2,2'
      #     label-meanings: 'You''re top 2 and you''re not number 2!|You are on the podium!|You have broken into the top 5!'
      #     days: 30
      #     category: 'hotlist'
