name: contributer-badge
on:
  workflow_dispatch: {}
  pull_request_target:
    types:
      - opened

jobs:
  call-action:
    runs-on: ubuntu-latest
    permissions:
      pull-request: write
    steps:
      - uses: kaizencc/contributer-badge@main
        id: contributer-badge
