name: contributer-badge
on:
  workflow_dispatch: {}
  pull_request_target:
    types:
      - opened
      - edited

jobs:
  call-action:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: kaizencc/contributor-badge@main
        id: contributor-badge-total
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'getting-started,all-star'
          buckets: '0,2'
          label-meanings: 'Nice job, you''ve opened a PR! Open 3 to get a special label!|WOW! You''ve committed a lot, well done!'
          category: 'total'
      - uses: kaizencc/contributor-badge@main
        id: contributor-badge-hotlist
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '1 :trophy:,top 3 :fire:,top 5 :sunglasses:'
          buckets: '1,2,2'
          label-meanings: 'you are in the top 2 and you''re not number 2!|you are on the podium!|you have broken into the top 5!'
          days: 30
          category: 'hotlist'
